[package]
name = "tfwr_external"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7.3"
rand = "0.8.5"
standard-dist = "1.0.0"
strum = "0.26.3"
strum_macros = "0.26.4"
